spring.application.name=order-service

server.port=8083

# Database
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Order;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Test@1234
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=*

# If 50% of requests fail, circuit breaker opens
resilience4j.circuitbreaker.instances.productService.failure-rate-threshold=50

# Once open, wait 10 seconds before allowing requests again
resilience4j.circuitbreaker.instances.productService.wait-duration-in-open-state=10000

# Number of requests used to calculate failure rate
resilience4j.circuitbreaker.instances.productService.sliding-window-size=2

# Minimum number of calls before calculating failure rate
resilience4j.circuitbreaker.instances.productService.minimum-number-of-calls=2
