spring.application.name=order-service

server.port=8083

# Database
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Order;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Test@1234
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=*


# RETRY CONFIG

# Number of total attempts (1 original + 2 retries = 3 total calls)
resilience4j.retry.instances.productService.maxAttempts=3
resilience4j.retry.instances.paymentService.maxAttempts=3

# Time gap between retry attempts (wait before next retry)
resilience4j.retry.instances.productService.waitDuration=500ms
resilience4j.retry.instances.paymentService.waitDuration=500ms


# CIRCUIT BREAKER CONFIG

# % of failures allowed before opening circuit
# Example: if 10 calls → 5 fail → 50% → circuit opens
resilience4j.circuitbreaker.instances.productService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentService.failureRateThreshold=50

# How long circuit stays OPEN (no calls allowed)
# After this, it moves to HALF_OPEN (test mode)
resilience4j.circuitbreaker.instances.productService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.paymentService.waitDurationInOpenState=10s

# TIME LIMITER CONFIG
# Maximum time to wait for response
# If service doesn't respond within 2 seconds → timeout exception
resilience4j.timelimiter.instances.productService.timeoutDuration=2s
resilience4j.timelimiter.instances.paymentService.timeoutDuration=2s


# BULKHEAD (THREAD POOL) CONFIG

# Minimum number of threads always available
# These threads are ready to handle requests immediately
resilience4j.thread-pool-bulkhead.instances.productService.coreThreadPoolSize=5
resilience4j.thread-pool-bulkhead.instances.paymentService.coreThreadPoolSize=5

# Maximum threads allowed during high load
# If more requests come, threads can increase up to this limit
resilience4j.thread-pool-bulkhead.instances.productService.maxThreadPoolSize=10
resilience4j.thread-pool-bulkhead.instances.paymentService.maxThreadPoolSize=10

# Queue size for waiting requests
# If all threads are busy, requests wait here
# If queue is full → request is rejected immediately
resilience4j.thread-pool-bulkhead.instances.productService.queueCapacity=20
resilience4j.thread-pool-bulkhead.instances.paymentService.queueCapacity=20

spring.kafka.consumer.group-id=order-group

server.forward-headers-strategy=framework
springdoc.api-docs.path=/orders/v3/api-docs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n
logging.level.root=INFO
